import {
  removeSpecialCharsSortingFn,
  LinkCell,
  ListCell,
  ListCellMembers,
  ProviderNameCell,
  countriesCell,
  fnName,
} from './utils';

const simple_columns = [
  {
    accessorFn: fnName,
    id: 'name',
    accessorKey: 'name',
    header: 'Name',
    cell: ProviderNameCell,
    sortingFn: removeSpecialCharsSortingFn,
    width: 250,
  },
  {
    accessorKey: 'link',
    header: 'Website',
    cell: LinkCell,
    width: 100,
    enableSorting: false,
    disableSortBy: true,
  },
  {
    accessorFn: (row) => row['countries'].join('|||'),
    id: 'countries',
    header: 'Countries',
    cell: countriesCell,
    width: 150,
    sortingFn: 'alphanumeric',
  },
  {
    accessorKey: 'provider_type',
    header: 'Type',
    width: 100,
    sortingFn: 'alphanumeric',
  },
  {
    accessorFn: (row) => row['services'].join('|||'),
    id: 'services',
    header: 'Copernicus Services',
    cell: ListCell,
    width: 150,
    sortingFn: 'alphanumeric',
  },
  {
    accessorFn: (row) => row['components'].join('|||'),
    id: 'components',
    header: 'Copernicus Components',
    cell: ListCell,
    width: 150,
    sortingFn: 'alphanumeric',
  },
];

const institution_columns = [
  {
    accessorFn: (row) => row['countries'].join('|||'),
    id: 'countries',
    header: 'Country',
    cell: countriesCell,
    width: 150,
    sortingFn: 'alphanumeric',
  },
  {
    accessorFn: fnName,
    id: 'name',
    accessorKey: 'name',
    header: 'Name',
    cell: ProviderNameCell,
    sortingFn: removeSpecialCharsSortingFn,
    width: 250,
  },
  {
    accessorKey: 'link',
    header: 'Website',
    cell: LinkCell,
    width: 150,
    enableSorting: false,
    disableSortBy: true,
  },
  {
    accessorKey: 'provider_type',
    header: 'Type',
    width: 100,
    sortingFn: 'alphanumeric',
  },
  {
    accessorFn: (row) => row['services'].join('|||'),
    id: 'services',
    header: 'Copernicus Services',
    cell: ListCell,
    width: 150,
    sortingFn: 'alphanumeric',
  },
  {
    accessorFn: (row) => row['components'].join('|||'),
    id: 'components',
    header: 'Copernicus Components',
    cell: ListCell,
    width: 150,
    sortingFn: 'alphanumeric',
  },
];

const network_columns = [
  {
    accessorFn: fnName,
    id: 'name',
    accessorKey: 'name',
    header: 'Name',
    cell: ProviderNameCell,
    sortingFn: removeSpecialCharsSortingFn,
    width: 200,
  },
  {
    accessorKey: 'link',
    header: 'Website',
    cell: LinkCell,
    enableSorting: false,
    disableSortBy: true,
    width: 150,
  },
  {
    accessorFn: (row) => row['countries'].join('|||'),
    id: 'countries',
    header: 'Countries',
    cell: countriesCell,
    width: 150,
    sortingFn: 'alphanumeric',
  },
  {
    accessorFn: (row) => JSON.stringify(row['members']),
    id: 'members',
    accessorKey: 'members',
    header: 'Members',
    cell: ListCellMembers,
    sortingFn: 'alphanumeric',
    width: 200,
  },
  {
    accessorFn: (row) => row['services'].join('|||'),
    id: 'services',
    header: 'Copernicus Services',
    cell: ListCell,
    width: 150,
    sortingFn: 'alphanumeric',
  },
  {
    accessorFn: (row) => row['components'].join('|||'),
    id: 'components',
    header: 'Copernicus Components',
    cell: ListCell,
    width: 150,
    sortingFn: 'alphanumeric',
  },
];

export { simple_columns, network_columns, institution_columns };
